# For production use, or when local development services need HTTPS
# https://doc.traefik.io/traefik/user-guides/docker-compose/acme-http/
services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    command:
      - --log.level=INFO
      #- --api.dashboard=true
      - --api.insecure=false
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --providers.docker=true
      - --providers.docker.network=traefik_network
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --entrypoints.web.http.encodedcharacters.allowencodedslash=true
    #labels:
      #- traefik.enable=true
      #- traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.com`) # Replace with your domain
      #- traefik.http.routers.traefik.entrypoints=websecure
      #- traefik.http.routers.traefik.tls=true
      #- traefik.http.routers.traefik.tls.certresolver=letsencrypt
      #- traefik.http.routers.traefik.service=api@internal
      #- traefik.http.routers.traefik.middlewares=auth
      #- traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_PW}

networks:
  proxy:
    name: traefik_network